import type {
  AdminVariableRecord,
  AuthUser,
  ItemRecord,
  ScheduleRecord,
  StatusEventRecord,
  StatusSnapshot,
  UserSettingsRecord,
  WorklogRecord,
} from "@/lib/types";

const now = "2026-05-08T09:00:00.000Z";
const yesterday = "2026-05-07T09:00:00.000Z";
const today = "2026-05-09T09:00:00.000Z";

export const demoStatus: StatusSnapshot = {
  backend: "Active",
  ai: "Local fallback",
};

export const demoUser: AuthUser = {
  id: "demo-user",
  email: "demo@local",
  isAdmin: true,
};

export const demoSettings: UserSettingsRecord = {
  nickname: "Demo user",
  worklogExportPath: "",
  customPrompt: "",
  calendarWeekStartsOn: "monday",
};

export const demoAdminVariables: AdminVariableRecord[] = [
  {
    id: "admin-var-1",
    key: "default_timezone",
    value: "Asia/Seoul",
    description: "Default timezone used by the app.",
    updatedAt: now,
  },
];

export const demoItems: ItemRecord[] = [
  {
    id: "item-1",
    itemType: "task",
    title: "업무 데이터 컬럼 매핑 정리",
    content: "source 스키마와 앱 내부 item 모델을 매칭합니다.",
    status: "doing",
    horizon: "now",
    priority: 1,
    source: "manual",
    project: "Scaffold Organizer",
    tags: ["schema", "mapping"],
    scheduledDate: null,
    dueDate: null,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-2",
    itemType: "thought",
    title: "장기 개선 아이디어 정리",
    content: "바로 실행하지 않을 제품 개선 아이디어를 장기 목록으로 유지합니다.",
    status: "todo",
    horizon: "long_term",
    priority: 4,
    source: "chat_input",
    project: "Product",
    tags: ["long-term"],
    scheduledDate: null,
    dueDate: null,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-3",
    itemType: "note",
    title: "Gemini command router 출력 검증",
    content: "명령 라우팅 JSON이 앱 action 모델과 맞는지 확인 필요",
    status: "inbox",
    horizon: "soon",
    priority: 3,
    source: "manual",
    project: "AI",
    tags: ["gemini"],
    scheduledDate: null,
    dueDate: null,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-4",
    itemType: "task",
    title: "SQLite schema를 Supabase schema로 이전",
    content: "enum, jsonb, uuid 기반으로 재작성",
    status: "done",
    horizon: "now",
    priority: 2,
    source: "system",
    project: "Migration",
    tags: ["supabase"],
    scheduledDate: null,
    dueDate: null,
    createdAt: now,
    updatedAt: now,
    completedAt: now,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-5",
    itemType: "task",
    title: "로그인 후 비로그인 화면 차단 플로우 확인",
    content: "production/auth-required 환경에서 실제 앱 화면이 노출되지 않는지 확인합니다.",
    status: "todo",
    horizon: "now",
    priority: 2,
    source: "manual",
    project: "Auth",
    tags: ["auth", "qa"],
    scheduledDate: "2026-05-09",
    dueDate: "2026-05-10",
    createdAt: yesterday,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-6",
    itemType: "task",
    title: "캘린더 월간 count UI 시각 검수",
    content: "일정, doing, done count가 같은 날짜에 겹쳐도 읽히는지 봅니다.",
    status: "doing",
    horizon: "now",
    priority: 3,
    source: "manual",
    project: "UI",
    tags: ["calendar", "responsive"],
    scheduledDate: "2026-05-09",
    dueDate: null,
    createdAt: now,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-7",
    itemType: "task",
    title: "모바일 390px 이하 카드 레이아웃 확인",
    content: "체크박스와 액션 버튼이 카드 폭을 밀어내지 않는지 확인합니다.",
    status: "todo",
    horizon: "soon",
    priority: 3,
    source: "manual",
    project: "UI",
    tags: ["mobile", "layout"],
    scheduledDate: "2026-05-11",
    dueDate: "2026-05-12",
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-8",
    itemType: "note",
    title: "관리자 변수 설명문이 길 때 wrapping 확인",
    content: "긴 description/value가 panel 밖으로 넘치지 않도록 meta text wrapping을 확인합니다.",
    status: "inbox",
    horizon: "later",
    priority: 4,
    source: "manual",
    project: "Admin",
    tags: ["admin", "text-wrap"],
    scheduledDate: null,
    dueDate: null,
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-9",
    itemType: "journal_seed",
    title: "Gemini 프롬프트 개인화 입력 테스트",
    content: "개인 custom prompt가 worklog와 command router에 반영되는지 확인할 샘플입니다.",
    status: "inbox",
    horizon: "soon",
    priority: 2,
    source: "brain_dump",
    project: "AI",
    tags: ["prompt", "personalization"],
    scheduledDate: null,
    dueDate: null,
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-10",
    itemType: "task",
    title: "Supabase RLS owner policy 재확인",
    content: "items, schedules, worklogs, user_settings가 user_id 기준으로 분리되는지 점검합니다.",
    status: "done",
    horizon: "now",
    priority: 1,
    source: "system",
    project: "Supabase",
    tags: ["rls", "security"],
    scheduledDate: "2026-05-08",
    dueDate: "2026-05-08",
    createdAt: yesterday,
    updatedAt: now,
    completedAt: now,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-11",
    itemType: "thought",
    title: "추후 Electron 래핑으로 로컬 경로 저장 지원",
    content: "브라우저 보안 제한 때문에 직접 경로 저장은 데스크톱 앱에서 재검토합니다.",
    status: "todo",
    horizon: "long_term",
    priority: 5,
    source: "chat_input",
    project: "Product",
    tags: ["desktop", "export"],
    scheduledDate: null,
    dueDate: null,
    createdAt: now,
    updatedAt: now,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-12",
    itemType: "task",
    title: "Work Log 페이지 안에서 생성/저장/다운로드 흐름 검수",
    content: "Generate Draft, Save, Download 버튼이 서로 헷갈리지 않는지 확인합니다.",
    status: "doing",
    horizon: "soon",
    priority: 2,
    source: "manual",
    project: "Worklog",
    tags: ["worklog", "ux"],
    scheduledDate: "2026-05-10",
    dueDate: null,
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-13",
    itemType: "task",
    title: "오래된 세션 API 제거 영향 확인",
    content: "브레인덤프 저장/불러오기 UI를 제거한 뒤 남은 링크나 버튼이 없는지 확인합니다.",
    status: "archived",
    horizon: "later",
    priority: 4,
    source: "system",
    project: "Cleanup",
    tags: ["session", "cleanup"],
    scheduledDate: null,
    dueDate: null,
    createdAt: yesterday,
    updatedAt: now,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-14",
    itemType: "note",
    title: "하늘색 강조색 contrast 확인",
    content: "흰색 배경 위에서 sky accent가 너무 약하지 않은지 확인합니다.",
    status: "todo",
    horizon: "later",
    priority: 4,
    source: "manual",
    project: "Design",
    tags: ["color", "accessibility"],
    scheduledDate: "2026-05-13",
    dueDate: null,
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-15",
    itemType: "task",
    title: "카드 350px 이상 다중 column 확인용 샘플",
    content: "데스크톱에서 auto-fill grid가 3열 이상으로 늘어나는지 확인합니다.",
    status: "todo",
    horizon: "now",
    priority: 3,
    source: "manual",
    project: "UI",
    tags: ["grid", "demo"],
    scheduledDate: "2026-05-09",
    dueDate: null,
    createdAt: today,
    updatedAt: today,
    completedAt: null,
    sessionId: null,
    externalRef: null,
  },
  {
    id: "item-16",
    itemType: "task",
    title: "완료 탭 카드 밀도 확인",
    content: "완료된 항목이 흐리게 보이면서도 제목은 읽히는지 확인합니다.",
    status: "done",
    horizon: "soon",
    priority: 3,
    source: "manual",
    project: "QA",
    tags: ["done", "visual"],
    scheduledDate: "2026-05-09",
    dueDate: null,
    createdAt: yesterday,
    updatedAt: today,
    completedAt: today,
    sessionId: null,
    externalRef: null,
  },
];

export const demoSchedules: ScheduleRecord[] = [
  {
    id: "schedule-1",
    title: "Supabase RLS 정책 검토",
    notes: "회원별 데이터 분리를 확인합니다.",
    scheduleDate: "2026-05-09",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-2",
    title: "디자인 QA 30분",
    notes: "카드 border, checkbox, column 수를 한 번에 확인합니다.",
    scheduleDate: "2026-05-09",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-3",
    title: "Gemini API 프롬프트 회고",
    notes: "개인 프롬프트와 관리자 변수를 어떤 식으로 합칠지 정리합니다.",
    scheduleDate: "2026-05-10",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-4",
    title: "모바일 화면 캡처 비교",
    notes: "390px, 768px, 1440px 화면을 비교합니다.",
    scheduleDate: "2026-05-11",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "schedule-5",
    title: "Supabase 수동 반영 체크",
    notes: "스키마 변경이 있는 경우 SQL Editor에서 반영합니다.",
    scheduleDate: "2026-05-13",
    createdAt: now,
    updatedAt: now,
  },
];

export const demoStatusEvents: StatusEventRecord[] = [
  {
    id: "event-1",
    itemId: "item-1",
    eventType: "status_change",
    fromStatus: "todo",
    toStatus: "doing",
    createdAt: "2026-05-08T09:00:00.000Z",
  },
  {
    id: "event-2",
    itemId: "item-6",
    eventType: "status_change",
    fromStatus: "todo",
    toStatus: "doing",
    createdAt: "2026-05-09T10:00:00.000Z",
  },
  {
    id: "event-3",
    itemId: "item-12",
    eventType: "status_change",
    fromStatus: "todo",
    toStatus: "doing",
    createdAt: "2026-05-09T11:00:00.000Z",
  },
  {
    id: "event-4",
    itemId: "item-10",
    eventType: "status_change",
    fromStatus: "todo",
    toStatus: "doing",
    createdAt: "2026-05-07T09:00:00.000Z",
  },
  {
    id: "event-5",
    itemId: "item-10",
    eventType: "status_change",
    fromStatus: "doing",
    toStatus: "done",
    createdAt: "2026-05-08T09:00:00.000Z",
  },
  {
    id: "event-6",
    itemId: "item-16",
    eventType: "status_change",
    fromStatus: "todo",
    toStatus: "doing",
    createdAt: "2026-05-08T15:00:00.000Z",
  },
  {
    id: "event-7",
    itemId: "item-16",
    eventType: "status_change",
    fromStatus: "doing",
    toStatus: "done",
    createdAt: "2026-05-09T15:00:00.000Z",
  },
  {
    id: "event-8",
    itemId: "item-4",
    eventType: "status_change",
    fromStatus: "todo",
    toStatus: "doing",
    createdAt: "2026-05-07T13:00:00.000Z",
  },
  {
    id: "event-9",
    itemId: "item-4",
    eventType: "status_change",
    fromStatus: "doing",
    toStatus: "done",
    createdAt: "2026-05-08T16:00:00.000Z",
  },
];

export const demoWorklogs: WorklogRecord[] = [
  {
    id: "worklog-1",
    logDate: "2026-05-08",
    title: "업무일지 — 2026-05-08",
    contentMd: "# 📅 업무일지 — 2026-05-08\n\n## 1. 🟢 오늘 착수한 작업\n- Next.js 마이그레이션 설계 시작\n",
    sourceSummary: {
      started: ["Next.js 마이그레이션 설계 시작"],
    },
    createdAt: now,
    updatedAt: now,
  },
];
